<?php


namespace App\Repositories\Store;


use App\Models\Store\News;
use App\Repositories\BaseRepository;
use Illuminate\Database\Eloquent\Builder;

/**
 * Class UserRepository
 * @package App\Repositories\System
 * @method News getModel()
 */
class NewsRepository extends BaseRepository
{

    protected array $relations = ['promoCode'];
    /**
     * UserRepository constructor.
     * @param News|null $model
     */
    public function __construct(News $model = null)
    {
        if($model === null) {
            $model = new News();
        }
        parent::__construct($model);
    }

    /**
     * @param array $data
     */
    protected function afterModification(array $data = []): void
    {
    }

    /**
     * @param array $conditions
     * @return Builder
     * @throws \App\Repositories\RepositoryException
     */
    protected function conditionsBuilder(array $conditions = []): Builder
    {
        return parent::conditionsBuilder($conditions); // TODO: Change the autogenerated stub

    }

}
