<?php


namespace App\Repositories\Store;


use App\Models\Store\Slider;
use App\Repositories\BaseRepository;
use Illuminate\Database\Eloquent\Builder;

/**
 * Class UserRepository
 * @package App\Repositories\System
 * @method Slider getModel()
 */
class SliderRepository extends BaseRepository
{

    /**
     * UserRepository constructor.
     * @param Slider|null $model
     */
    public function __construct(Slider $model = null)
    {
        if ($model === null) {
            $model = new Slider();
        }
        parent::__construct($model);
    }

    /**
     * @param array $data
     */
    protected function afterModification(array $data = []): void
    {
    }

    /**
     * @param array $conditions
     * @return Builder
     * @throws \App\Repositories\RepositoryException
     */
    protected function conditionsBuilder(array $conditions = []): Builder
    {
        $builder = parent::conditionsBuilder($conditions); // TODO: Change the autogenerated stub

        if (array_key_exists('target', $conditions) && is_string($conditions['target'])) {
            $builder->where('target', '=', $conditions['target']);
        }

        return $builder;
    }

}
