<?php


namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class Login extends FormRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            'phone'      => 'required|phone:RU',
            'password'   => 'required|min:3',
            'utms'       => 'array',
            'deviceInfo' => 'array',
        ];

    }

    public function messages()
    {
        return [
            'phone.phone' => 'Некоректный телефон',
            'phone.required' => 'Поле Логин обязательное для заполнения',
        ]; // TODO: Change the autogenerated stub
    }
}
