<?php

namespace App\Http\Controllers\CRM\Store;

use App\Http\Controllers\CRM\BaseCRMController;
use App\Http\Requests\CRM\Setting\{UpdateSettingRequest, StoreSettingRequest};
use App\Http\Resources\CRM\SettingResource;
use App\Services\CRM\Store\SettingService;


class SettingController extends BaseCRMController
{
    public function __construct(SettingService $service)
    {
        parent::__construct($service, StoreSettingRequest::class, UpdateSettingRequest::class, SettingResource::class);
    }


    protected function conditions(): array
    {
        $conditions = parent::conditions(); // TODO: Change the autogenerated stub

        $conditions['name'] = request()->get('name');
        $conditions['key'] = request()->get('key');
        $conditions['filialId'] = request()->get('filialId');

        return $conditions;
    }

    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function getSetting()
    {

        $setting = $this->service->getFormatSettingByConditions($this->conditions());

        return $this->responseSuccess($setting);
    }

}
