<?php

namespace App\Http\Controllers\Web\Menu;

use App\Http\Controllers\Web\BaseWebController;
use App\Http\Resources\Web\MenuItemResource;
use App\Libraries\BasketUpsellingItems;
use App\Models\Order\Basket;
use App\Services\Web\Menu\MenuItemService;


class MenuItemController extends BaseWebController
{

    public function __construct(MenuItemService $service)
    {
        parent::__construct($service,MenuItemResource::class);
    }



    public function index()
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws \App\Repositories\RepositoryException
     * @throws \App\Services\CRM\CRMServiceException
     */
    public function upSellingItems()
    {
        $upSelling = new BasketUpsellingItems(new Basket());

        return $this->respondWithCollection($upSelling->getUpSellingItems());
    }

    public function show(string $searchParam)
    {
        return parent::show($searchParam); // TODO: Change the autogenerated stub
    }
}
