<?php


namespace App\Repositories\System;

use App\Models\System\Call as CallModel;
use App\Repositories\BaseRepository;
use Illuminate\Database\Eloquent\Builder;

/**
 * Class UserRepository
 * @package App\Repositories\System
 * @method CallModel getModel()
 */
class CallRepository extends BaseRepository
{
    protected array $relations = ['client'];

    /**
     * CallRepository constructor.
     * @param CallModel|null $model
     */
    public function __construct(CallModel $model = null)
    {

        if ($model === null) {
            $model = new CallModel();
        }

        parent::__construct($model);
    }

    protected function afterModification(array $data = []): void
    {

    }


    protected function conditionsBuilder(array $conditions = []): Builder
    {
        $query = parent::conditionsBuilder($conditions); // TODO: Change the autogenerated stub

        return $query;
    }
}
