<?php


namespace App\Repositories\System;

use App\Models\System\ClientDevice as ClientDeviceModel;
use App\Repositories\BaseRepository;
use Illuminate\Database\Eloquent\Builder;

/**
 * Class UserRepository
 * @package App\Repositories\System
 * @method ClientDeviceModel getModel()
 */
class ClientDeviceRepository extends BaseRepository
{

    /**
     * UserRepository constructor.
     * @param ClientDeviceModel|null $model
     */
    public function __construct(ClientDeviceModel $model = null)
    {
        if ($model === null) {
            $model = new ClientDeviceModel();
        }

        parent::__construct($model);
    }

    /**
     * @param array $data
     */
    protected function afterModification(array $data = []): void
    {
    }

    /**
     * @param array $conditions
     * @return Builder
     * @throws \App\Repositories\RepositoryException
     */
    protected function conditionsBuilder(array $conditions = []): Builder
    {
        $builder = parent::conditionsBuilder($conditions); // TODO: Change the autogenerated stub

        if (array_key_exists('agent', $conditions) && !is_array($conditions['agent'])) {
            $builder->where('agent', '=', $conditions['agent']);
        }

        if (array_key_exists('device', $conditions) && !is_array($conditions['device'])) {
            $builder->where('device', '=', $conditions['device']);
        }

        if (array_key_exists('clientId', $conditions) && is_numeric($conditions['clientId'])) {
            $builder->where('client_id', '=', $conditions['clientId']);
        }


        if (array_key_exists('deviceId', $conditions) && !is_array($conditions['deviceId'])) {
            $builder->where('device_id', '=', $conditions['deviceId']);
        }

        if (array_key_exists('logoutAt', $conditions)) {
            $builder->where('logout_at', '=', $conditions['logoutAt']);
        }

        return $builder;
    }

}
