<?php


namespace App\Repositories\System;

use App\Models\System\CourierGeo as CourierGeoModel;
use App\Repositories\BaseRepository;
use Illuminate\Database\Eloquent\Builder;

/**
 * Class UserRepository
 * @package App\Repositories\System
 * @method CourierGeoModel getModel()
 */
class CourierGeoRepository extends BaseRepository
{
    protected array $relations = ['user'];

    /**
     * CourierGeoRepository constructor.
     * @param CourierGeoModel|null $model
     */
    public function __construct(CourierGeoModel $model = null)
    {

        if ($model === null) {
            $model = new CourierGeoModel();
        }

        parent::__construct($model);
    }

    protected function afterModification(array $data = []): void
    {

    }


    protected function conditionsBuilder(array $conditions = []): Builder
    {
        $query = parent::conditionsBuilder($conditions); // TODO: Change the autogenerated stub

        return $query;
    }
}
