<?php


namespace App\Repositories\System;


use App\Models\System\FilialCashBox as FilialCashBoxModel;
use App\Repositories\BaseRepository;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Carbon;

/**
 * Class UserRepository
 * @package App\Repositories\System
 * @method FilialCashBoxModel getModel()
 */
class FilialCashBoxRepository extends BaseRepository
{
    protected array $relations = ['transactions','filial'];

    /**
     * FilialCashBoxRepository constructor.
     * @param FilialCashBoxModel|null $model
     */
    public function __construct(FilialCashBoxModel $model = null)
    {

        if ($model === null) {
            $model = new FilialCashBoxModel();
        }

        parent::__construct($model);
    }



    protected function afterModification(array $data = []): void
    {

    }

    protected function conditionsBuilder(array $conditions = []): Builder
    {
        $query = parent::conditionsBuilder($conditions); // TODO: Change the autogenerated stub



        if(array_key_exists('filialId',$conditions) && is_numeric($conditions['filialId'])) {
            $query->where('filial_id','=',$conditions['filialId']);
        }

        if (array_key_exists('closeAt', $conditions)) {
            if (is_string($conditions['closeAt'])) {
                $query->whereDate('close_at', '=', $conditions['closeAt']);

            } elseif ($conditions['closeAt'] === null) {
                $query->whereNull('close_at');
            }
        }

        if(array_key_exists('openAt',$conditions)) {
            $query->whereDate('open_at','=',$conditions['closeAt']);
        }

        if(array_key_exists('day',$conditions) && $conditions['day'] === 'today') {
            $query->where('date','=', Carbon::now()->toDateString());
        }elseif(array_key_exists('date',$conditions) && is_string($conditions['date'])) {
            $query->where('date','=',$conditions['date']);
        }

        return $query;
    }
}
