<?php


namespace App\Repositories\System;

use App\Models\System\Payment as PaymentModel;
use App\Repositories\BaseRepository;
use Illuminate\Database\Eloquent\Builder;

/**
 * Class UserRepository
 * @package App\Repositories\System
 * @method PaymentModel getModel()
 */
class PaymentRepository extends BaseRepository
{
    protected array $relations = ['order'];

    /**
     * PaymentRepository constructor.
     * @param PaymentModel|null $model
     */
    public function __construct(PaymentModel $model = null)
    {

        if ($model === null) {
            $model = new PaymentModel();
        }

        parent::__construct($model);
    }

    protected function afterModification(array $data = []): void
    {

    }

    protected function conditionsBuilder(array $conditions = []): Builder
    {
        $query = parent::conditionsBuilder($conditions); // TODO: Change the autogenerated stub

        return $query;
    }
}
