<?php


namespace App\Repositories\System;

use App\Models\System\Request as RequestModel;
use App\Repositories\BaseRepository;
use Illuminate\Database\Eloquent\Builder;

/**
 * Class UserRepository
 * @package App\Repositories\System
 * @method RequestModel getModel()
 */
class RequestRepository extends BaseRepository
{
    protected array $relations = ['client','filial'];

    /**
     * RequestRepository constructor.
     * @param RequestModel|null $model
     */
    public function __construct(RequestModel $model = null)
    {

        if ($model === null) {
            $model = new RequestModel();
        }

        parent::__construct($model);
    }

    protected function afterModification(array $data = []): void
    {

    }


    protected function conditionsBuilder(array $conditions = []): Builder
    {
        $query = parent::conditionsBuilder($conditions); // TODO: Change the autogenerated stub

        return $query;
    }
}
