<?php


namespace App\Repositories\System;


use App\Models\System\WorkSpace as WorkSpaceModel;
use App\Repositories\BaseRepository;
use Illuminate\Database\Eloquent\Builder;



/**
 * Class UserRepository
 * @package App\Repositories\System
 * @method WorkSpaceModel getModel()
 */
class WorkSpaceRepository extends BaseRepository
{

    protected array $relations = ['filial','role'];
    /**
     * WorkSpaceRepository constructor.
     * @param WorkSpaceModel|null $model
     */
    public function __construct(WorkSpaceModel $model = null)
    {

        if ($model === null) {
            $model = new WorkSpaceModel();
        }

        parent::__construct($model);
    }



    /**
     * @param array $data
     */
    protected function afterModification(array $data = []): void
    {
    }


    protected function conditionsBuilder(array $conditions = []): Builder
    {
        $query = parent::conditionsBuilder($conditions); // TODO: Change the autogenerated stub

        if (array_key_exists('filialId', $conditions) && is_numeric($conditions['filialId'])) {
            $query->where('filial_id', '=', $conditions['filialId']);
        }
        if (array_key_exists('phoneAccount', $conditions) && is_numeric($conditions['phoneAccount'])) {
            $query->where('phone_account', '=', $conditions['phoneAccount']);
        }

        return $query;
    }
}
