<?php

namespace App\Http\Controllers\Web\Information;


use App\Http\Controllers\Web\BaseWebController;
use App\Http\Resources\Web\NewsResource;

use App\Libraries\Cache;
use App\Services\Web\Information\NewsService;

/**
 * Class NewsController
 * @package App\Http\Controllers\Web\Catalog
 */
class NewsController extends BaseWebController
{

    /**
     * NewsController constructor.
     * @param NewsService $service
     */
    public function __construct(NewsService $service)
    {
        parent::__construct($service, NewsResource::class);
    }

    public function index()
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }
    public function show(string $searchParam)
    {
        return parent::show($searchParam); // TODO: Change the autogenerated stub
    }
}
