<?php

namespace App\Http\Controllers\Web\Information;


use App\Http\Controllers\Web\BaseWebController;
use App\Http\Resources\Web\SliderResource;


use App\Services\Web\Information\SliderService;

/**
 * Class SliderController
 * @package App\Http\Controllers\Web\Catalog
 */
class SliderController extends BaseWebController
{

    /**
     * SliderController constructor.
     * @param SliderService $service
     */
    public function __construct(SliderService $service)
    {
        parent::__construct($service, SliderResource::class);
    }

    public function index()
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }
    public function show(string $searchParam)
    {
        return parent::show($searchParam); // TODO: Change the autogenerated stub
    }
}
