<?php


namespace App\Services\CRM\System;


use App\Repositories\System\PolygonRepository;
use App\Services\CRM\CRMBaseService;

/**
 * Class PolygonService
 * @package App\Services\CRM\System
 * @method PolygonRepository getRepository()
 */
class PolygonService extends CRMBaseService
{

    public function __construct(?PolygonRepository $repository = null)
    {
        parent::__construct($repository);
    }


    protected function dataCorrection(array $data)
    {
        $data = parent::dataCorrection($data); // TODO: Change the autogenerated stub



        if (array_key_exists('price', $data) && is_numeric($data['price'])) {
            $data['price'] *= 100;
        }

        if (array_key_exists('freeFromPrice', $data) && is_numeric($data['freeFromPrice'])) {
            $data['freeFromPrice'] *= 100;
        }

        return $data;
    }
}
