<?php


namespace App\Services\CRM\System;


use App\Events\Request\CreateRequest;
use App\Repositories\System\RequestRepository;
use App\Services\CRM\CRMBaseService;


/**
 * Class UserService
 * @package App\Service\System
 *
 * @method RequestRepository getRepository()
 */
class RequestService extends CRMBaseService
{
    /**
     * RequestService constructor.
     * @param RequestRepository|null $repository
     * @throws \App\Services\CRM\CRMServiceException
     */
    public function __construct(?RequestRepository $repository = null)
    {
        parent::__construct($repository);
    }

    public static function add(array $data)
    {
        return parent::add($data); // TODO: Change the autogenerated stub
    }

    public function events()
    {
        CreateRequest::dispatch($this->getRepository()->getModel());
        parent::events(); // TODO: Change the autogenerated stub
    }

}
