<?php


namespace App\Services\CRM\Courier;


use App\Enums\TransactionStatus;
use App\Repositories\Courier\TransactionRepository;
use App\Services\CRM\CRMBaseService;
use App\Services\CRM\CRMServiceException;
use App\Services\CRM\System\UserService;

/**
 * Class TransactionService
 * @package App\Services\CRM\Store
 * @method TransactionRepository getRepository()
 */
class TransactionService extends CRMBaseService
{


    public function __construct(?TransactionRepository $repository = null)
    {

        parent::__construct($repository);
    }

    /**
     * @param array $data
     * @return array
     * @throws \App\Repositories\RepositoryException
     * @throws \ReflectionException
     */
    protected function dataCorrection(array $data): array
    {
        $data = parent::dataCorrection($data); // TODO: Change the autogenerated stub


        if (array_key_exists('price', $data) && is_numeric($data['price'])) {
            $data['price'] *= 100;
        }


        return $data;

    }


}
