<?php


namespace App\Services\CRM\Store;


use App\Repositories\Store\SettingRepository;
use App\Services\CRM\CRMBaseService;

/**
 * Class SettingService
 * @package App\Services\CRM\System
 * @method SettingRepository getRepository()
 */
class SettingService extends CRMBaseService
{

    public function __construct(?SettingRepository $repository = null)
    {
        parent::__construct($repository);
    }

    /**
     * @param array $data
     * @return array
     */
    protected function dataCorrection(array $data): array
    {
        $data = parent::dataCorrection($data); // TODO: Change the autogenerated stub

        if (array_key_exists('value', $data) && is_array($data['value'])) {
            $data['json'] = true;
            $data['value'] = json_encode($data['value']);
        }

        return $data;
    }


    /**
     * @param $conditions
     * @return array
     * @throws \App\Repositories\RepositoryException
     * @throws \ReflectionException
     */
    public function getFormatSettingByConditions($conditions) : array
    {
        $settingService = self::findOne($conditions);

        return $settingService->getRepository()->formatSetting($conditions['filialId']);
    }


}
