<?php


namespace App\Http\Controllers\CRM\System;


use App\Http\Controllers\CRM\BaseCRMController;
use App\Http\Requests\CRM\Permission\CreatePermission;
use App\Http\Requests\CRM\Permission\UpdatePermission;
use App\Http\Resources\CRM\PermissionResource;
use App\Services\CRM\System\PermissionService;

class PermissionController extends BaseCRMController
{
    public function __construct(PermissionService $service)
    {
        parent::__construct($service,CreatePermission::class,UpdatePermission::class,PermissionResource::class);
    }


    /**
     * @return \Illuminate\Http\JsonResponse
     * @throws \ReflectionException
     */
    public function index()
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }



}
